### ISSUE TITLE
[FEATURE]-Lighting Level Feedback

### ISSUE THREAD

**Issue by jonnyarndt** [PepperDash/epi-lighting-denton-cor-tap#5]
**Is your feature request related to a problem? Please describe.**
Please add polling mechanism to request lighting level feedback. Lighting fixture level could be controlled by local keypad. Would be good to keep both Crestron and keypad in-sync. Would be a good day-2 feature.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ngenovese11** [comment]
fixed in PR
